In [258]:
import matplotlib.pyplot as plt
import numpy as np

In [259]:
# 任意の整数
m = 6

In [260]:
# 符号長
n = 2**m - 1
# 情報数
k = n - m

In [261]:
np.set_printoptions(precision=0,threshold=100000,linewidth=np.inf)
# 検査行列
H = np.zeros((m, n))
# 右側を単位行列にする
for i in range(m):
    H[i][k + i] = 1
# 左側はランダム
H_set = set()
H_set.add(0)
for i in range(m):
    H_set.add(1 << i)
for i in range(k):
    while True:
        h = np.random.randint(low=0, high=2, size=(m, 1))
        sum_h = 0
        for j in range(m):
            sum_h += h[j, 0] << j
        if sum_h not in H_set:
            H[:, i] = h.reshape(-1)
            H_set.add(sum_h)
            break
print("---検査行列---")
for h in H:
    print(np.int64(h), sep="\t")
print(np.linalg.matrix_rank(H[:, :k]))
# 情報列
x = np.random.randint(low=0, high=2, size=k)
print("---情報列---")
print(np.int64(x), sep="\t")
# 生成行列
G = np.concatenate([np.identity(k), H[:, :k].T], axis=1)
print("---生成行列---")
for g in G:
    print(np.int64(g), sep="\t")
# 符号列
w = x @ G % 2
print("---符号列---")
print(np.int64(w), sep="\t")

---検査行列---
[1 1 1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1 0 0 1 0 1 1 0 1 1 1 0 0 1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 0 1 0 1 0 0 0 0 0]
[1 0 1 1 1 1 1 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 1 0 1 0 0 1 0 1 0 0 1 1 1 1 1 0 1 1 0 1 0 1 0 1 0 1 0 0 1 0 1 0 0 0 1 0 1 0 0 0 0]
[0 1 1 0 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 0 0 0 0 1 0 0 1 0 1 1 1 0 1 1 1 1 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 1 0 0 1 0 0 0]
[0 1 0 1 1 1 1 1 0 0 1 1 1 0 1 1 1 0 0 0 0 0 0 1 0 1 0 1 1 1 0 0 1 1 0 0 0 1 0 0 0 1 0 1 1 1 1 1 0 1 0 1 1 1 1 0 0 0 0 0 1 0 0]
[0 0 1 1 1 0 0 1 1 0 0 0 1 0 1 1 0 1 1 0 1 1 1 1 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 1 1 1 0 0 1 1 0 1 1 0 1 1 1 0 0 0 0 1 0]
[1 1 0 0 0 0 1 0 1 1 0 1 1 0 1 1 1 1 1 0 1 1 0 0 0 1 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 1 1 0 1 1 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 1]
6
---情報列---
[0 1 0 0 1 1 1 1 0 1 1 0 1 1 1 0 0 1 1 1 1 0 0 0 0 1 1 0 1 1 1 1 0 0 1 1 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0]
---生成行列---
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [262]:
# チェック(正しく伝送された場合)
result = H @ w.T % 2
print("---誤りなし---")
print(np.int64(result), sep="\t")
# チェック(1ビット誤り)
print("---1ビット誤り---")
for i in range(n):
    wi_old = w[i]
    w[i] = (w[i] + 1) % 2
    result = H @ w.T % 2
    print(f"{i+1}ビット目が誤った場合: {np.int64(result)}", sep="\t")
    w[i]=wi_old

---誤りなし---
[0 0 0 0 0 0]
---1ビット誤り---
1ビット目が誤った場合: [1 1 0 0 0 1]
2ビット目が誤った場合: [1 0 1 1 0 1]
3ビット目が誤った場合: [1 1 1 0 1 0]
4ビット目が誤った場合: [0 1 0 1 1 0]
5ビット目が誤った場合: [1 1 0 1 1 0]
6ビット目が誤った場合: [0 1 0 1 0 0]
7ビット目が誤った場合: [0 1 1 1 0 1]
8ビット目が誤った場合: [0 0 0 1 1 0]
9ビット目が誤った場合: [0 0 0 0 1 1]
10ビット目が誤った場合: [0 0 1 0 0 1]
11ビット目が誤った場合: [0 0 1 1 0 0]
12ビット目が誤った場合: [1 1 0 1 0 1]
13ビット目が誤った場合: [1 1 1 1 1 1]
14ビット目が誤った場合: [1 0 1 0 0 0]
15ビット目が誤った場合: [1 1 0 1 1 1]
16ビット目が誤った場合: [0 0 1 1 1 1]
17ビット目が誤った場合: [0 0 1 1 0 1]
18ビット目が誤った場合: [0 0 1 0 1 1]
19ビット目が誤った場合: [1 1 1 0 1 1]
20ビット目が誤った場合: [1 1 0 0 0 0]
21ビット目が誤った場合: [1 1 0 0 1 1]
22ビット目が誤った場合: [0 1 0 0 1 1]
23ビット目が誤った場合: [0 1 0 0 1 0]
24ビット目が誤った場合: [1 0 0 1 1 0]
25ビット目が誤った場合: [0 1 1 0 1 0]
26ビット目が誤った場合: [1 0 0 1 1 1]
27ビット目が誤った場合: [1 0 0 0 0 1]
28ビット目が誤った場合: [0 1 1 1 0 0]
29ビット目が誤った場合: [1 0 0 1 0 1]
30ビット目が誤った場合: [1 1 1 1 0 0]
31ビット目が誤った場合: [1 0 1 0 1 0]
32ビット目が誤った場合: [0 0 1 0 1 0]
33ビット目が誤った場合: [0 1 0 1 0 1]
34ビット目が誤った場合: [1 1 1 1 0 1]
35ビット目が誤った場合: [1 1 